### ISSUE TITLE
[CHORE] - Random Array Utility

### ISSUE THREAD

**Issue by nhcarrigan** [RosaliaNightsong/discord-bot#135]
### What work needs to be performed?

Within the `utils` directory, we should create a simple function named `getRandomValue`. This function should take an array and return a random item from the array.

Then, we should update the rest of the code base to use this instead of repeated `Math.random()` calls.

**Comment by nhcarrigan** [comment]
All yours!

**Comment by ArnavPuri** [comment]
After implementing the function and replacing the occurrences of `randomIndex`. I am getting these warnings when I run `npm run lint`.

<img width="1256" alt="Screenshot 2021-10-16 at 2 12 47 PM" src="https://user-images.githubusercontent.com/4078339/137580933-22cf4a2e-e51a-4105-b721-5fe88c8c8e4e.png">

The function `getRandomValue` will return `any` item depending on the array provided as input. So should I ignore these warnings and submit a PR?

**Comment by ArnavPuri** [comment]
Actually, the only place we are returning an object (instance of `Adventure`) instead of `string` is in the file `handleSearch.ts`. And even in that file, we are using `newArea.name` everywhere which is a string. So maybe I can update `getRandomValue` to always return a string and refactor the code in `handleSearch.ts` file.

<img width="1018" alt="Screenshot 2021-10-16 at 2 32 27 PM" src="https://user-images.githubusercontent.com/4078339/137581938-fca554c2-b8cc-4114-b5fc-54ebf8d3046d.png">

**Comment by KrzysztofCzopek** [comment]
@ArnavPuri you can use generics to match the returned element type to the type of the array:
```ts
function getRandomElement<T>(...elements: T[]): T {
  // implementation here
}
```

**Comment by ArnavPuri** [comment]
Thanks, @KrzysztofCzopek for the suggestion. I have implemented that and now it is passing the lint tests.
